"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=cmb^r$q+7_3rm^e(h1xt--k#6uh0oha_=tpd!evfmt$34_@(m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost","127.0.0.1","*"]


# Application definition

INSTALLED_APPS = (
    #'django_admin_bootstrapped',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',
    'blog',
)

CKEDITOR_UPLOAD_PATH='uploads/'
CKEDITOR_IMAGE_BACKEND='pillow'
CKEDITOR_CONFIGS = {
    'default':{
        'skin':'moono',
        'height':500,
        'widget':900,
        'toolbar':[
            ['div','Source','-','Save','NewPage','Preview','-','Templates'], 
            ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Print','SpellChecker','Scayt'], 
            ['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'], 
            ['Form','Checkbox','Radio','TextField','Textarea','Select','Button', 'ImageButton','HiddenField'], 
            ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'], 
            ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote'], 
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'], 
            ['Link','Unlink','Anchor'], 
            ['CodeSnippet','CodeMirror','Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak'], 
            ['Styles','Format','Font','FontSize','TextColor','BGColor'], 
            ['Maximize','ShowBlocks','-','About', 'pbckcode'],
            ],
        'extraPlugins':'sourcedialog,codemirror,widget,lineutils,codesnippet,selectall',
        'codemirror' : {
            'theme': 'default',
            'lineNumbers': True,
            'lineWrapping': True,
            'matchBrackets': True,
            'autoCloseTags': True,
            'autoCloseBrackets': True,
            'enableSearchTools': True,
            'enableCodeFolding': True,
            'enableCodeFormatting': True,
            'autoFormatOnStart': False,
            'autoFormatOnModeChange': False,
            'autoFormatOnUncomment': False,
            'highlightActiveLine': True,
            'mode': 'htmlmixed',
            'showSearchButton': True,
            'showTrailingSpace': True,
            'highlightMatches': True,
            'showFormatButton': True,
            'showCommentButton': True,
            'showUncommentButton': True,
            'showAutoCompleteButton': True,
        },
        'allowedContent' : True,
    },
}

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
	#'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'myblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'myblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
		'ENGINE':'django.db.backends.mysql',
		'OPTIONS':{
			'read_default_file':'/etc/my.cnf',
			#'init_commend':'SET storage_engine=INNODB',
		},
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh_CN'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static')
#STATICFILES_DIRS = (
	#os.path.join(BASE_DIR,'static'),
	#'/var/www/html/myblog/commonstatic',
#	)
